NDefines.NCountry.MIN_MAJOR_COUNTRIES = 2
NDefines.NCountry.ADDITIONAL_MAJOR_COUNTRIES_IC_RATIO = 100
NDefines.NCountry.MAX_HEROES_BEING_KILLED_WAR_SUPPORT_IMPACT = -0.4
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_INFRA = 0.5
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_VP = 20
NDefines.NCountry.THERMONUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_INFRA = 0.5
NDefines.NCountry.THERMONUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_VP = 20
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30